apiVersion: v1
kind: Service
metadata:
  name: dwk-project-svc
spec:
  type: NodePort
  selector:
    app: dwk-project # This is the app as declared in the deployment.
  ports:
    - name: http
      nodePort: 30080 # Any request sent to all nodes in the cluster at port 30080 will be forwarded to targetPort
      protocol: TCP
      port: 7777 # Any request sent to this service at port 7777 will be forwarded to targetPort
      targetPort: 7777 # This is the target port
