apiVersion: v1
kind: Service
metadata:
  name: dwk-ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-ping-pong
  ports:
    - port: 2345 
      protocol: TCP
      targetPort: 7777 # This is the target port