apiVersion: v1
kind: Service
metadata:
  name: dwk-project-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-project
  ports:
    - port: 2345 # Any request sent to this service at port 7777 will be forwarded to targetPort
      protocol: TCP
      targetPort: 7777 # This is the target port
