apiVersion: v1
kind: Service
metadata:
  name: dwk-project-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-project
  ports:
    - port: 7777
      name: todo-app
      protocol: TCP
      targetPort: 7777
    - port: 7778
      name: todo-backend
      protocol: TCP
      targetPort: 7778
